server:
  port: 8080
logging: 
  file: /data/logs/springboot1-learn/application.log

spring:
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?prepStmtCacheSize=517&cachePrepStmts=true&autoReconnect=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
       minimum-idle:25
       maximum-pool-size:55
       connection-test-query:SELECT 1
       max-lifetime:1800000
       connection-timeout:30000
       pool-name:DatebookHikariCP
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      
#    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ntabase?useSSL=false
#    username: postgres
#    password: 123456
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate: 
#      ddl-auto: update
#    properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQL94Dialect
    
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000
    pool:
      max-active: 32
      max-wait: 3000
      max-idle: 16
      min-idle: 8
    
  kafka:
    producer: 
      bootstrap-servers: 127.0.0.1:9092
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
#  elasticsearch: 
#    jest:
#      uris:
#      - http://localhost:9200
#      read-timeout: 5000

project: 
  version: v1.0.0
  name: yml测试开发版本
  